### PR TITLE
Chore(Revit): remove batch uploader from running in the background

### PR DESCRIPTION
**Pull request by connorivy**
## Description & motivation

Batch uploader was never fully viable and should not be running in the connector because it doesn't do anything

### CODE REVIEW

**Review by BovineOx — APPROVED** [review]
@JR-Morgan should have a sanity check but looks legit to me - we ought to have a ticket on the board though

**Review by JR-Morgan — APPROVED** [review]

**Review by AlanRynne — DISMISSED** [review]
If this fully disables BatchUploader, we should also pull the references from all the revit csproj files.

**Review by JR-Morgan — CHANGES_REQUESTED** [review]
Good catch Alan

**Comment by AlanRynne** [comment]
Tested this locally and nothing breaks, managed to send/receive just fine without the BatchUploader as expected.

**Review by JR-Morgan — APPROVED** [review]

**Pull request merged**
