### PR TITLE
Replaced triangle net source with nuget

### PR DESCRIPTION
**Pull request by JR-Morgan**
@phliberato

### CODE REVIEW

**Comment by JR-Morgan** [comment]
Good point @phliberato, there are also some unknowns on our end with packaging so let's leave this for now.
I'll ask @teocomi what he thinks of us publishing the triangle net on our nugets

**Comment by teocomi** [comment]
> Good point @phliberato, there are also some unknowns on our end with packaging so let's leave this for now. I'll ask @teocomi what he thinks of us publishing the triangle net on our nugets

We already have several nugets, so would be happy to do so for this one too :)

**Comment by AlanRynne** [comment]
Reopened this now that we have our own NuGet published!

**Review by AlanRynne — APPROVED** [review]
I'm blessing my own changes 🙌🏼

**Pull request merged**
