### PR TITLE
fix(Revit): Dockable panel initialization not working when launching Dockable Revit form a file

### LINKED ISSUE #1469: Dockable panel initialization not working when launching Revit form a file
If launching Revit by double-clicking on a Revit file (instead of first launching Revit and then opening a file) the initialization of the Dockable Panel is not working and throws `The requested dockable pane has not been created yet.`

This seems to be an issue with the Revit API as the panel under both circumstances is actually registered and initialized correctly.

As a matter of fact, as a workaround, **opening another Revit file** is correctly starting the dockable panel.

**Steps to repro**

1. Add command line args to launch revit file:

image

2. Click debug
3. After the project has been opened, click on the Speckle command

**Solution tried**

I tried to simplify, and force a re-registration of the panel when clicking on the ribbon button, to no avail.
I also tried changing when the panel is first initialized from the `Idle` to the a `ControlledApplication.ApplicationInitialized` event.

Some more details:

```
        var p1 = DockablePane.PaneIsRegistered(PanelId);  //true
        var p2 = DockablePane.PaneExists(PanelId); //false
        var p3 = App.AppInstance.GetDockablePane(PanelId); //throws "The requested dockable pane has not been created"
```

Also, no events like `DocumentOpened`, or `ViewActivated` are triggered under these circumstances.

image

### PR DESCRIPTION
**Pull request by Mehdi-Lucas**
## Description & motivation

The Dockable Pane wasn't initializing correctly when users opened Revit by double-clicking a file. Previously, the Speckle add-in would handle this by displaying an error message instructing the user to create a new file or open Revit first for a correct pane initialization. While this approach served as a workaround, it proved sometimes cumbersome for users, especially those with automated batch jobs that automatically opened files, as highlighted in a user's (@GianClaudioScarafini ) [comment](https://github.com/specklesystems/speckle-sharp/issues/1469#issuecomment-1812486081) in the linked issue #1469.

In my development of an add-in for my client, which also utilizes a DockablePane, I aimed for a more seamless experience and sought to avoid workarounds. I discovered that the issue arose because the DocumentOpening event was being triggered before the ApplicationInitialized event. Consequently, the DockablePane wasn't registered at that point, leading to its malfunction.

To resolve this, I implemented a solution where the pane registration occurs during both the DocumentOpening and ApplicationInitialized events. However, since two events can call the pane creation now, it's essential to check whether the pane has already been registered and created before proceeding with the registration process during these events. 
 
Fix #1469 
## Changes:

Revit Connector

## To-do before merge:

Please ensure that this modification does not impact the behavior of the connector in other aspects. While my tests suggest it's working, due to time constraints, I couldn't delve deeply into the intricacies of Speckle domain logics. It's prudent to verify that all changes still function as intended.

Particularly, scrutinize the bindings creation process, as I have made adjustments to accommodate their addition during the DocumentOpening events to ensure smooth UI creation. 

And let me know If some clarification is required or if there are any uncertainties.

## Validation of changes:

Manual testing by opening multiple files. Do not hesistate to test on more file/scenarios.
Here is the behavior with the Pane not being created when double clicking a file (before the change):
dockablePaneBefore

Here is the behavior with the Pane being correctly created when double clicking a file (after the change):
dockablePaneAfter

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [x] I have updated or added relevant documentation. (I added comments)

### CODE REVIEW

**Comment by BovineOx** [comment]
@Mehdi-Lucas thanks so much for this, I've scheduled a task to get this in, in our next sprint (starting week tomorrow)

**Comment by Mehdi-Lucas** [comment]
> @Mehdi-Lucas thanks so much for this, I've scheduled a task to get this in, in our next sprint (starting week tomorrow)

You're welcome 👍 good to hear and I'm hopeful that it will be working and validated on your end. Should you require any further information, please feel free to reach out :)

**Comment by connorivy** [comment]
Hey @Mehdi-Lucas 

This is awesome, I tested and it works great. We tried to solve this issue a while ago, but didn't think to try to documentOpening event.

Unfortunately we let this PR sit here for a bit too long and some of the files have had other changes which led to some difficult merge conflicts. Instead of resolving those, I just made a new PR which does exactly the same thing this PR does.

https://github.com/specklesystems/speckle-sharp/pull/3311.

Once that gets merged we will close this one.

**Comment by Mehdi-Lucas** [comment]
Hi @connorivy,

I'm pleased to hear that my fix has been tested and is working well :) This will certainly improve Speckle users experience, especially those running batch jobs.

I had a quick look this morning and updated my branch to the latest commit on main. I successfully built it, but you are probably talking about merge conflicts on another branch, possibly dev. Unfortunately, given my current work priorities, I won't have a lot of time this days to dedicate to the Speckle open-source project and address those conflicts promptly, possibly before the new PR you've opened gets merged

If you could somehow resolve those conflicts on my PR/Branch, I would greatly appreciate it. I trust you'd understand why it's better on my side.

If not, it's okay 👍

**Comment by connorivy** [comment]
@Mehdi-Lucas 

Yes this is a feature that is being added to our `dev` branch. If you'd like, then you can retarget your PR to dev. We were intending to give you author credit when merging the branch that we have open. Is that just as good? Or would you rather have this PR merged with the fixes?

**Comment by Mehdi-Lucas** [comment]
> We were intending to give you author credit when merging the branch that we have open. Is that just as good? 

Alright, I suppose this should work 👍 thanks

**Comment by AlanRynne** [comment]
Closing this in favor of  #3255 which has already been merged into `dev` with the proper attribution to you @Mehdi-Lucas 🙌🏼

Thanks again for taking the time to fix some annoying limitations we had! 🚀 

You whould be getting this in the next release 2.19, but an `alpha` version will likely be released soon. We'll ping you so you can give it a shake.

**Comment by Mehdi-Lucas** [comment]
You are welcome. It seems there's a slight mix-up: PR #3255 is this one, but I believe you intended to reference PR #3311

>  Let's remember to add the original author as a contributor in the PR merge comment so they get the GitHub cred 
I'm not accustomed to this kind workflow, it have been merged indeed but I might have overlooked where my name appears in that PR. Thanks in any case, I trust it has/will be done.

**Comment by AlanRynne** [comment]
Oh! Yeah I must have mixed up my links! 😅  Sorry about that.

This is somewhat a weird git thing: GitHub doesn't show you as part of the PR, but we added you as a co-author in the PR comment before merging, so you appear as one of the authors of this change in the git-history (which then propagates into the contributors list in GitHub)

Just double-checked just to be sure and there you are 👇🏼
Screenshot 2024-04-26 at 12 17 54

**Pull request closed without merging**
