### PR TITLE
[WIP] Unify to .net6

### PR DESCRIPTION
**Pull request by martijn00**
The current state of the repo and code is hard to maintain and build. By moving to .net6 it is lots easier and code can be improved.

This is a starting point and if this is the correct approach I can pick up the work to complete this.

## Changes:

Update project files, references and code to work with .net6

## To-do before merge:

Validate that everything works.

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by teocomi** [comment]
Hey @martijn00 thanks for this PR.
We cannot update Core to .net6 because, AFAIK, it cannot be referenced by older .NET Frameworks (basically all our connectors): https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

We could, though, add additional `<TargetFrameworks>` if needed.

Also, please note that in your PR you are replacing our `Speckle.Newtonsoft.Json` with `Newtonsoft.Json`. That can't be done, we are purposely using a fork to avoid dll hell in various host applications.

**Comment by martijn00** [comment]
@teocomi it should be possible to update most of those to .net6 too? Adding Additional `TargetFrameworks` only works when using the new project system, which is not used in the connectors.

The problem with `Speckle.Newtonsoft.Json` is that this way applications can't trim their code on that level, and need to include their own Newtonsoft version. I was planning to replace it with `System.Text.Json` anyways because that is the new standard.

Are there things that I should know that prevent this?

**Comment by martijn00** [comment]
I understand that this is quite a change, and shouldn't be merged overnight or anything. Still quite a lot of work need to go into something like this, and needs testing on your side.

My motivation is that we are about to start quite a big new project that uses Speckle and if we want or need to make changes to the source, the current state of the repo makes it hard. In the long term it is necessary to move to a unified dotnet experience based on .net6 or 7. I think the timing is right because of things like desktop support in .net6. This opens up for lots of improvements to the code and speed optimalizations as well.

Maybe something that helps on your end is my experience with something like this. I'm a long time Microsoft MVP on .NET, and creator of library's like MvvmCross, Lottie, Exoplayer for .NET.

For Newtonsoft, wouldn't it be possible to use binding redirects? In the end I think it should still move to System.Text.Json. Unless there is something very special in the code I can't think of a reason not to do it in .net6 or 7. It should be compatible too. But maybe a good strategy is to cut that up into another PR?

**Comment by teocomi** [comment]
Thanks for the extra context, @martijn00; how about we jump on a quick call to discuss? 

https://calendly.com/d/z2z-hnh-2y2/15-min-chat

**Comment by martijn00** [comment]
Do you have time in 5min?

**Comment by AhmedZero** [comment]
it'll be better .Net 7 too, there is a lot of improvement in performance.
I don't know why Autodesk doesn't upgrade its .NET Framework 4.7.2 to .NET 6 or 7?

**Comment by chuongmep** [comment]
I also a same issue before, https://github.com/specklesystems/speckle-sharp/issues/1273. This is a good to maintain, I know that, but need to consider because some SDK of Autodesk still base on .Net Framework, I guess maybe need 2-3 year for Autodesk to can upgrade it to net 7 or net standard .

**Comment by teocomi** [comment]
Hey @martijn00 , we're closing this for now as .net 6 is not supported in most of the host applications where our Connectors run. 
Happy to discuss more if needed - you know where to find us! :)

**Pull request closed without merging**
