### PR TITLE
fix(revit): send objects in family document

### PR DESCRIPTION
**Pull request by Zhuangkh**
## Description & motivation

fixes https://github.com/specklesystems/speckle-sharp/issues/1928

## Changes:

Determine whether it is in the family document.

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

https://github.com/specklesystems/speckle-sharp/issues/1928

### CODE REVIEW

**Comment by teocomi** [comment]
Looks good to me!
We might also want to change https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs#L161 to support sending `CombinableElement `

**Comment by teocomi** [comment]
Hey @Zhuangkh let us know if you're still working on this, I see it's still makes as draft :)

**Comment by Zhuangkh** [comment]
HI @teocomi ，sorry for not updating for so long (🥲covid and a busy working time)，I will pull the latest code to re-evaluate this PR

**Comment by Zhuangkh** [comment]
hey @teocomi , I want to know how Speckle handles void geometry, I can't seem to find it in the current code. Void is a big part of the family document.

**Comment by teocomi** [comment]
Hey @Zhuangkh ,

Thanks for this; I'm afraid we currently do not support sending or receiving Revit forms (extrusion, blend, sweep).
We could look at adding support, but I'm not sure there are many valid use cases for this.
Generally, being able to receive Brep geometry is enough, on sending it seems this would only be beneficial in Revit<>Revit workflows...

What do you think? @bimgeek might have some opinions on this too :)

**Comment by connorivy** [comment]
hi @Zhuangkh,

Currently we don't do anything special to handle voids, the extrusion voids are handled the same as any other family instance. You can see a bit of that current behavior in a gif [here](https://speckle.community/t/openings-voids-in-revitfloor-and-revitwall/3005/10). Basically we just place the void family instances and Revit then figures out if that instance is a void and if it needs to cut it's host geometry. Can you treat these voids the same as other extrusions while setting the BuiltInParameter.ELEMENT_IS_CUTTING and the BuiltInParameter.VOID_CUTS_GEOMETRY parameters to tell Revit to treat it as a void?

**Comment by Zhuangkh** [comment]
> Generally, being able to receive Brep geometry is enough, on sending it seems this would only be beneficial in Revit<>Revit workflows...

In my opinion, it is not speckle's responsibility to create a family document (send/receive `CombinableElement(extrusion, blend, sweep)` in the family document) . Speckle does collaboration between projects (correct me if I'm wrong🥲). It’s much less meaningful if only synchronize geometry but not parametric family. This is why I said in https://github.com/specklesystems/speckle-sharp/issues/1928#issuecomment-1330881633 whether it is necessary to support.

> setting the BuiltInParameter.ELEMENT_IS_CUTTING and the BuiltInParameter.VOID_CUTS_GEOMETRY parameters to tell Revit to treat it as a void

Got it😋

**Comment by teocomi** [comment]
@Zhuangkh if it's easy, we could just send the mesh representation of these `CombinableElement`.
Otherwise the PR might just be enough as it is :)

**Comment by Zhuangkh** [comment]
image

Temporarily use `freeform` to upload and download, two issues in progress: void geometry & material when received

**Comment by connorivy** [comment]
Hi @Zhuangkh 

I'm looking this over and it looks pretty good, thanks for making the PR! One question I have for you, do you know why some of the more complicated geometries are failing to be received back in the family model? I'm frequently getting this error 
image

**Comment by Zhuangkh** [comment]
@connorivy One possible reason is that the `Triangulate` process in `GetMeshesFromSolids` produces some edge less than the minimum length. I'm not sure, need to run some tests

**Comment by teocomi** [comment]
> Hi @Zhuangkh
> 
> I'm looking this over and it looks pretty good, thanks for making the PR! One question I have for you, do you know why some of the more complicated geometries are failing to be received back in the family model? I'm frequently getting this error !

@AlanRynne and I have seen this error a lot in the Family Editor... It might be just a Revit bug.
@Zhuangkh let us know if you find out anything :)

**Comment by Zhuangkh** [comment]
@teocomi I have no idea. I have tested several exception cases, the mesh data looks correct. And I tried different build parameters for tsb and probably got InternalException. Maybe you are right, it is really a bug in Revit :(

**Pull request merged**
