### PR TITLE
fix(Revit,Navis): resolve unsafe dll error

### PR DESCRIPTION
**Pull request by connorivy**
## Changes:

- hook up OnAssemblyResolve logic to load dlls before any other logic

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

https://speckle.community/t/speckle-2-for-revit-could-not-load/5301/5

### CODE REVIEW

**Comment by chuongmep** [comment]
#relate #2338

**Comment by jsdbroughton** [comment]
> #relate #2338

Do you think this resolves your issue @chuongmep ?

**Comment by chuongmep** [comment]
@jsdbroughton confirm, problem resolved in my company computer after pull this request.

**Review by AlanRynne — APPROVED** [review]
🙇🏼‍♂️ Sorry I think I moved these guys 2 lines too far up when trying to fix the initialisation of the logger.

Approved!

**Pull request merged**
