### PR TITLE
Fix(Revit): add conversion support for TopRail elements associated with Railing elements 

### LINKED ISSUE #1507: Bug: Top Railing geometry not sent from Revit
## What package are you referring to?

Revit Connector

## Describe the bug

Revit connector doesn't send top railing from Revit. See GIF below👇

## To Reproduce

1. Create a railing in Revit
2. Select it and send it to Speckleverse
3. Investigate it in the viewer or receive it in another software

## Expected behavior

I was expecting it to send it.

## Screenshots
Revit_Nkcaz7jhoK

### PR DESCRIPTION
**Pull request by Ibrahim5aad**
## Description & motivation

The converted `Railing` elements misses it's associated `TopRail` elements.
Fixes #1507. 

## Changes:

 - Add `TopRailToSpeckle` converter method to convert `TopRail` elements to Speckle objects.
- Modify the `RailingToSpeckle` converter method to collect the `TopRail` associated element if there is any.
- The collected `TopRail` element is checked against `ContextObjects` and `ConvertedObjectsList` to prevent double conversion; the same way as wall/floor/.. hosted elements.
- Modify `RailingToNative` converter method to check if the `Railing` type has the correct associated `TopRail` type.

## Screenshots:

Screenshot 2022-08-28 194633

## Validation of changes:

Manual tests for sending and receiving in Revit.

## Checklist:
 
- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by teocomi** [comment]
Hey @Ibrahim5aad thanks a lot for this PR! 
Can you please change your editor indentation to be 2 spaces? It seems not to have picked the `.editorconfig` file in the solution. 

Changing that will make the review easier ;)

**Comment by Ibrahim5aad** [comment]
> Hey @Ibrahim5aad thanks a lot for this PR! Can you please change your editor indentation to be 2 spaces? It seems not to have picked the `.editorconfig` file in the solution.
> 
> Changing that will make the review easier ;)

**Comment by Ibrahim5aad** [comment]
Thanks @teocomi  

Yeah my editor didn't pick the editorconfig file for some reason. Can you check now is the last commit fixed this?

**Comment by teocomi** [comment]
Hey @Ibrahim5aad , the PR looks great, you even accounted for the issue of duplicated elements, which is great :)
I was wondering if we really need to have a separate class for the Top Rail, or if instead we could just take its mesh and put it in the `DisplayMesh` of the main railing element?
Would it create any problems when receiving in Revit? As far as I understand, the Top railing is created automatically with the Railing itself...

**Comment by Ibrahim5aad** [comment]
@teocomi  

You are right, but not entirely (I think?). I tried to follow this line of thought as the `TopRail` element is created automatically as you said by just controlling the required `Railing` type parameters. So when converting to native Revit elements, you don't need all of this, even the mesh geometry of the `TopRail` is not of any use. But this led me to a point that this PR didn't cover; the `TopRail` parameters when converting back to native.

The `TopRail` category is of course a sub-category of the `Railing` category, but you could have parameters that lives on the sub-category only not the parent, and of course different parameter values. So you'll need to preserve the `TopRail` parameter list. Which something I didn't take care of before my last commit.

**Comment by teocomi** [comment]
Gotcha @Ibrahim5aad ! Thanks for the reply, and sorry for my slow answer; we're in the middle of a release :)
If you could resolve the new conflict that have popped up, I'll be happy to merge then!

**Comment by Ibrahim5aad** [comment]
Here you go, @teocomi. All set up now. I fixed the conflicts and give it a test on my side.

**Review by teocomi — APPROVED** [review]

**Pull request merged**
