### PR TITLE
Add Nunit Test Point Geometry

### PR DESCRIPTION
**Pull request by chuongmep**
## Description & motivation

This is the first base for test library for Point geometry. Will be updated for Vector, Geometry,... after that.
- [x] Point
## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [x] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Review by teocomi — APPROVED** [review]

**Comment by teocomi** [comment]
Thanks!

**Comment by JR-Morgan** [comment]
@teocomi  `Objects/Tests` project already exists, do we want `Objects/NUnit` also?

**Comment by teocomi** [comment]
Txs @JR-Morgan I hadn't realized! @chuongmep can you please add your tests to https://github.com/specklesystems/speckle-sharp/blob/release/2.10/Objects/Tests/Tests.csproj instead?

**Comment by chuongmep** [comment]
@JR-Morgan @teocomi Test is break now. Don't have reference in project. Can we add it to project first ? 
image

**Comment by JR-Morgan** [comment]
`Object/Test/Tests.csproj` maybe missing from `All.sln`, feel free to add.

**Comment by chuongmep** [comment]
Added. Thank you, let me create another pull request add collaborate to this.

**Pull request merged**
