### PR TITLE
core: hotfix for sqlite transport swallowing exception when failing t…

### PR DESCRIPTION
**Pull request by JR-Morgan**
This PR contains a small subset of the changes already merged in `dev` for 2.16 regarding transport exception handling - https://github.com/specklesystems/speckle-sharp/pull/2700

The problem with the SQLite transport, is if it fails to initialize a connection to the DB, it "calls" OnErrorAction. However, there is no way for OnErrorAction to be assigned, since this is performed in the constructor.

So in effect, this is a silent swallow of any exceptions that occur when initializing a connection to the DB.

This leaves the transport in an invalid state such that calls to its members will fail with no-descript error messages.

This PR replaces the false call to OnErrorAction with a throw - as per the changes already made in dev. This way callers are aware of their failed sqlite connection

### CODE REVIEW

**Comment by JR-Morgan** [comment]
As @tsvilans is [no longer blocked](https://speckle.community/t/c-null-argument-when-receiving-from-sqltransport-with-known-object-id/6416/4) by this, we might not bother hot fixing this for 2.15.

The functional change is already in 2.16 `dev` branch.

**Comment by didimitrie** [comment]
Happy with it, my only fears were re release. Merge away!

**Review by didimitrie — APPROVED** [review]

**Comment by AlanRynne** [comment]
So is this to be merged?

> The functional change is already in 2.16 `dev` branch.

I can't find any commit in the `dev` branch that has this,

**Comment by AlanRynne** [comment]
Sorry, closed PR by mistake while writing a comment 🙇🏼‍♂️

**Comment by JR-Morgan** [comment]
The exact commit is not on dev, but the change is https://github.com/specklesystems/speckle-sharp/blob/d05449583efc8499ce25adaf4e7880bfa302baf4/Core/Core/Transports/SQLite.cs#L64

I've merged now

**Pull request merged**
