### PR TITLE
Csharpier CSI

### PR DESCRIPTION
**Pull request by JR-Morgan**
Renamed `Partial Classes` to `PartialClasses`.
Ran csharpier on CSI converter.

### CODE REVIEW

**Review by AlanRynne — COMMENTED** [review]
YES 🙌🏼 May be tricky to merge this in right now though... so not approving... YET

**Comment by JR-Morgan** [comment]
My other PR https://github.com/specklesystems/speckle-sharp/pull/2970 is full for formatting changes since I have been editing these files with the csharpier "on save" hook.

This makes this PR quite messy, so I was hoping that I could get this one in first (being that it's 100% formatting changes)
then hopefully the diff for https://github.com/specklesystems/speckle-sharp/pull/2970 will be cleaner.

If this messes other peoples PRs up however, I can hold off for a bit.

**Review by connorivy — APPROVED** [review]
Merging this won't be an issue for me

**Comment by AlanRynne** [comment]
Fantastic! Merging in then ;)

**Pull request merged**
