### PR TITLE
feat(core): stream permissions / invites for server >=2.7 

### LINKED ISSUE #1434: Core: Implement New Invite Strategy
2 Core tests are failing due to a miss-alignment with `speckle-server`: https://app.circleci.com/pipelines/github/specklesystems/speckle-sharp/6736/workflows/73f23ab4-72df-46ff-9767-5e084f965972/jobs/19064

Change was introduced here https://github.com/specklesystems/speckle-server/commit/da9224a069cace19087952fcfa610c84726eb854

### PR DESCRIPTION
**Pull request by izzylys**
## Description & motivation

Updates the mutations around server invites to align with server changes from v2.7 onwards. 

closes #1434 

## Changes:

- moves the `ServerInfo` model to `Api.Models` (used to be in `Credentials.Responses`
- adds new models for stream invites 
- adds `GetServerVersion` query which populates a `ServerVersion` prop on the client
- adds stream invite create / invite use / invite get mutations
- adds updated permissions mutations
- also updates a couple small things in DesktopUI (but does not add ui for new mutations)
- tests for all of this

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [x] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by izzylys** [comment]
this PR is safe to merge despite tests not passing

all tests passed on this both locally and initially in the ci

https://app.circleci.com/pipelines/github/specklesystems/speckle-sharp/7093/workflows/ddb0395d-97c8-4418-a67b-fcff8d4764b6/jobs/23133

post merging / resolving conflicts with `release/2.8`, unit tests are hanging for mysterious reasons. 
unit tests also fail on the release branch (though they weren't previously triggered due to a ci issue).

**Review by AlanRynne — APPROVED** [review]
Yay! Looks good 🥳

Wish the tests weren't hanging but they pass in my machine

**Comment by AlanRynne** [comment]
Just updated the branch to have the fix for the broken tests :)

**Comment by izzylys** [comment]
ty ily 💕✨

**Pull request merged**
