### PR TITLE
fix(revit): better handling of built-in-categories 

### PR DESCRIPTION
**Pull request by clairekuang**
## Description & motivation

Fixes issues of failed railing creation due to improper sending and retrieval of built in categories for revit 2023 and 2024.

This pr mirror ths logic used by schema builder to remove "OST_" from bic internal names to find the equivalent RevitCategory, when before we were just using the category name. This was causing issues in differentiating between "OST_Railings" and "OST_StairsRailing" bics because they both had the category name of "Railing". Also seems to have fixed some issues in native railing conversion by retrieving the correct type.

## Screenshots:

image

Railings now received on fallback conversion:
image

### CODE REVIEW

**Comment by martinromby** [comment]
Hi @clairekuang 
Any chance that you could provide a list of category names prior and after the implementation of this PR? 
We have a small whitlisting of category names, so that would be good to update accordingly when this is released. 

Thanks.

**Review by AlanRynne — APPROVED** [review]
We discussed this yesterday but forgot to ✅ after our call.

**Comment by clairekuang** [comment]
@martinromby No worries, there are no changes to the actual list of `RevitCategory` enums we support ([link](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Objects/BuiltElements/Revit/Enums.cs)).

The only difference is that before, some elements were not being sent with the correct enum as their category. Before this PR, railings of built-in type `OST_StairsRailing` were being sent with `category = Railings`, and now they are being sent with `category = StairsRailing`

**Comment by martinromby** [comment]
@clairekuang Thanks for clarifying.
I'm on the latest pre-release, Revit 2024 and same Sample Project as you, but the Railing still seem to be translate to `category = Railings`. 
Not sure if we should update the whitelist with `StairsRailing` or not. 

Here's a commit on the xyz server:
https://speckle.xyz/streams/c1b3bb896b/commits/282d31594b

**Comment by clairekuang** [comment]
@martinromby Are you able to receive this railing in your file, if you set the `Fallback to DirectShape on Receive` setting to `Always`? Just want to check that it's not a bic type difference between your 2024 file and my 2023 file.
image

**Comment by clairekuang** [comment]
@martinromby You should see the updated categories with the next pre-release, after this pr has been merged!

**Pull request merged**
