### PR TITLE
Fix package ref DriverPluginCSharp

### PR DESCRIPTION
**Pull request by chuongmep**
## Description & motivation

Resolve problem with package reference

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by teocomi** [comment]
Hey @chuongmep, thanks as usual :)

Not really sure why this is needed? The projects build fine for me inside `ConnectorCSI.sln`

**Comment by chuongmep** [comment]
@teocomi it have problem with some people clone project in the fist time and open All.sln

**Comment by teocomi** [comment]
I can't seem to replicate :) is it Ok to close this?

**Comment by chuongmep** [comment]
> I can't seem to replicate :) is it Ok to close this?

You are using `rider`. That is problem with rider, I use 3 computer, 2 laptop and 1 PC for both rider and visual studio, just rider is have this problem, please check again.

**Comment by chuongmep** [comment]
Yes, please help me confirm it , if don't have any problem in `rider` 2022.3  from your side, I will close this request.

**Pull request closed without merging**
