### PR TITLE
Fix: Adds material quantities to MEP elements

### LINKED ISSUE #2117: materialQuantities missing on certain Revit Categories
The `materialQuantities` object is missing on the following Revit Categories:

- Ducts (needs to be specified for the actual duct thickness)
- Duct Insulation
- Flex Ducts
- Flex Pipes
- Pipes
- Railings
- Ramps

### PR DESCRIPTION
**Pull request by ks-cph**
## Description & motivation

Fixes #2117 (partly)

Current implementation does not find materials for `Autodesk.Revit.DB.MEPCurve`. 
https://github.com/specklesystems/speckle-sharp/blob/f7b188f73a909abddf09b96d892edc747439943b/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertMaterialQuantities.cs#L49

With the update, they have a material in `materialQuantities` once converting the elements to speckle.

Does not solve #2117 for Railings and Ramps.

## Changes:

- if-clause checking if the revit element is of type `Autodesk.Revit.DB.MEPCurve`
- query material using an existing method from `Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs`
- The existing method `GetMEPSystemMaterial()` does the same, but here we need the revit material and not the converted material. Hence, I split the method instead of copying the same code.

## Screenshots:
<p float="left">
  before
  After
</p>
Before (left) and after (right)

## Validation of changes:
Manually tested with elements from subclasses of `MEPCurve`.

- Duct
- FlexDuct
- DuctInsulation
- Pipe
- FlexPipe
- PipeInsulation
- Conduit
- CableTray
- Wire

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by teocomi** [comment]
Thanks for the PR @ks-cph ! It looks simple enough - we'll review it and include it in the current release cycle.

**Comment by connorivy** [comment]
Hey @ks-cph,

For some reason this code isn't working for me. I've sent several mep elements using this branch and none of them have the material quantities prop. Here is one example of something I've sent using the code from this PR https://latest.speckle.dev/streams/85bc4f61c6/commits/29f6763efe

**Comment by ks-cph** [comment]
@connorivy 
Thanks for the response. Did you assign material to the elements in Revit? I could add a line that a default material is used if no material is found.

If you assigned a material, I need to investigate it further. In Revit, the material is set in the system types for ducts and pipes.

**Comment by ks-cph** [comment]
Hi @connorivy,
I am quite sure that the way they assign the material in the reference is only a workaround for their specific problem.

In Revit, each MEP element has a SystemType assigned. Here you can specify a material.



<p float="left">
  
  systemtype

</p>


I share a very simple Revit file where I tested it: https://1drv.ms/u/s!At37Mwx2Fk9FgaVjYrBLtLy-ndL9HA?e=Vu747V
The corresponding speckle stream is https://speckle.xyz/streams/44eda9bd0e

Please let me know if it is still not clear or if I can help anyhow.

Cheers,
Kilian

**Review by connorivy — APPROVED** [review]

**Pull request merged**
